config/routes.rb
Rails.application.routes.draw do



  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  devise_for :users
    root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  def completed?
    !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user
  has_many :todo_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end

  def destroy
    @todo_item =@todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = "Todo List item was deleted"
    else
      flash[:error] = "Todo List item could not be deleted."
    end
    redirect_to @todo_list
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to  @todo_list, notice: "Todo item completed"
  end

  private
  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def set_todo_item
    @todo_item =@todo_list.todo_items.find(params[:id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params.merge(:user_id => current_user.id))
    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-primary">
  <div class="nav navbar-nav">
    <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
    <a class="nav-item nav-link" href="surveys/new">Create new survey</a>
    <a class="nav-item nav-link" href="#">Results</a>
    <a class="nav-item nav-link" href="#">About</a>
  </div>
</nav>

app/views/layouts/_headerindex.html.erb
<nav class="navbar navbar-dark bg-primary">
  <div class="nav navbar-nav">
    <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
    <a class="nav-item nav-link" href="surveys">Show all surveys</a>
    <a class="nav-item nav-link" href="#">Results</a>
    <a class="nav-item nav-link" href="#">About</a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Tangerine">
    <title><%= content_for?(:title) ? yield(:title) : "HTW Todo List" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">HTW Todo List</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Todo Lists", "/todo_lists"  %></li>
            <li><%= link_to "logout", destroy_user_session_path, method: :delete  %></li>
            <li><%= link_to "About", "#"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Media Programming 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "new Todo" %>
  <%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<table>
<tbody>
<div>
  <% if todo_item.completed? %>
      <td><div>
        <%= link_to  complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
          <i style="opacity: 0.4;" class="fa fa-check"></i>
        <% end %>
      </div></td>
      <td><div>
        <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
      </div></td>
      <td><div>
        <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "Are you sure?"} do %>
          <i class="fa fa-trash"></i>
        <% end %>
      </div></td>
  <% else %>
      <td><div>
        <%= link_to  complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
            <i class="fa fa-check"></i>
        <% end %>
      </div></td>
      <td><div>
        <p><%= todo_item.content %></p>
      </div></td>
      <td><div>
        <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "Are you sure?"} do %>
            <i class="fa fa-trash"></i>
        <% end %>
      </div></td>
   <% end %>
</div>
</tbody>
</table>

app/views/todo_lists/_form.html.erb
<%= form_for(todo_list) do |f| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>
      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <table class="table table-hover">
      <thead>
      <tr>
        <th><strong>Title</strong></th>
        <th><strong>Description</strong></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
        <td><%= f.text_field :title %></td>
        <td><%= f.text_area :description %></td>
        <td>  <div class="actions">
          <%= f.submit %>
        </div></td>
      </tbody>
    </table>


<% end %>

app/views/todo_lists/edit.html.erb
<h2>Editing Todo List</h2>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Todo Lists</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <%-# if current_user.id == todo_list.id %>
          <td><%= todo_list.title %></td>
          <td><%= todo_list.description %></td>
          <td><%= link_to 'Show', todo_list %></td>
          <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
          <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%-# end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo List', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h2>New Todo List</h2>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-hover">
  <thead>
  <tr>
    <th><strong>Title</strong></th>
    <th><strong>Description</strong></th>
    <th><strong>Items</strong></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
    <td><%= @todo_list.title %></td>
    <td><%= @todo_list.description %></td>
    <td><%= render @todo_list.todo_items %></td>
  </tbody>
  <tbody>
  <td><div id="form">
    <%= render "todo_items/form" %>
  </div></td>
  </tbody>



</table>
<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>

app/views/welcome/index.html.erb
<p id="notice"><%= notice %></p>



<body>
<div class="container">
  <center><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Logo_HTW_Berlin.svg/1024px-Logo_HTW_Berlin.svg.png" width="200" height="100"
       img align="center" class="img-fluid" alt="Responsive image"></center>
</div>
<div>
  <%= link_to "Todo List", todo_lists_path, method: :get %>
</div>
<div>
  <%= link_to "logout", destroy_user_session_path, method: :delete  %>
</div>
</body>